plugins {
    id 'talky.base-conventions'
    id 'talky.java-conventions'
    id 'talky.spring-boot-conventions'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation project(':auth-core')
    implementation project(':storage:chat-db')
    implementation 'io.hypersistence:hypersistence-tsid:2.1.4'

    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:mongodb'
    testImplementation 'org.testcontainers:junit-jupiter'
}