plugins {
    id 'talky.base-conventions'
    id 'talky.java-conventions'
    id 'talky.spring-boot-conventions'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation project(':storage:chat-db')

    testImplementation 'io.projectreactor:reactor-test'
}
1