/**
 * 플러그인 선언
 * - apply false: 버전만 정의하고 실제 적용은 서브모듈에서 선택적으로 함
 * - 서브모듈에서 버전 없이 id만 선언하면 여기서 정의한 버전을 사용
 */
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

/**
 * 전체 프로젝트 공통 설정 (루트 + 서브모듈)
 */
allprojects {
    group = 'org.talky'
    version = '1.0-SNAPSHOT'
}

/**
 * 서브모듈 공통 설정 (루트 제외)
 */
subprojects {
    apply plugin: 'java'

    java {
        sourceCompatibility = '21'
        targetCompatibility = '21'
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'

        testImplementation platform('org.junit:junit-bom:5.9.1')
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }

    test {
        useJUnitPlatform()
    }
}
