plugins {
    id 'talky.base-conventions'
    id 'talky.java-conventions'
    id 'talky.spring-boot-conventions'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.security:spring-security-crypto'
    implementation 'nl.basjes.parse.useragent:yauaa:7.28.1'
    implementation 'io.hypersistence:hypersistence-tsid:2.1.4'
    implementation project(':auth-core')
    implementation project(':storage:platform-db')

    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'com.h2database:h2'
}
